apiVersion: apps/v1
kind: Deployment
metadata:
  name: depnginx
  annotations:
    kubernetes.io/change-cause: "Udating to latest"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: depnginx
  template:
    metadata:
      labels:
        app: depnginx
    spec:
      containers:
      - name: depnginx
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "125m"
        ports:
        - containerPort: 80
