apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    name: pod-1
spec:
  containers:
  - name: ngnix
    image: suraj49470/dockernodeapp
    resources:
      limits:
        memory: 128Mi
        cpu: 250m
  
