---
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    name: pod-1
    env: dev
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: 128Mi
        cpu: 250m
...
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    name: pod-2
    env: prod
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: 128Mi
        cpu: 250m
...
