apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicontainer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multicontainer
  template:
    metadata:
      labels:
        app: multicontainer
    spec:
      containers:
      - name: dockernodeapp1
        image: nginx:stable-alpine3.17-slim
        resources:
          limits:
            memory: "128Mi"
            cpu: "125m"
        ports:
        - containerPort: 80 
